name: Heimdall
main: org.morganm.heimdall.Heimdall
version: 0.3
author: morganm
softdepend: [LogBlock]
commands:
  heimdall:
    aliases: [heim]
    description: Admin control functions for Heimdall
    permission: heimdall.admin
    usage: /<command> reload - reload the config file
    executor: org.morganm.heimdall.commands.Heimdall
  hdi:
    description: Ignore Heimdall alerts for a given player
    permission: heimdall.admin
    usage: /<command> player - ignore all alerts related to player
    executor: org.morganm.heimdall.commands.AdminNotifyIgnore
  hgl:
    description: Show last 5 grief log entries for a given player
    permission: heimdall.admin
    usage: /<command> player - show grief log for player
    executor: org.morganm.heimdall.commands.GriefLog
